CREATE TABLE `core_serial_number` (
  `ID` varchar(36) NOT NULL,
  `PREFIX` varchar(36) DEFAULT NULL,
  `CURRENT_TAG` int(12) DEFAULT NULL,
  `UPDATE_TIME` datetime DEFAULT NULL,
  `UPDATE_SERVER` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `ltp_demo` (
  `ID` varchar(36) NOT NULL,
  `AUTO_ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(36) DEFAULT NULL,
  `CODE` varchar(36) DEFAULT NULL,
  PRIMARY KEY (`AUTO_ID`),
  UNIQUE KEY `ID` (`ID`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=12 DEFAULT CHARSET=utf8mb4;

